# Generated by Django 5.1.3 on 2024-11-10 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('fulfilled', 'Fulfilled'), ('in_progress', 'In Progress'), ('stalled', 'Stalled'), ('broken', 'Broken')], max_length=20)),
                ('date_promised', models.DateField()),
                ('date_updated', models.DateField(auto_now=True)),
            ],
        ),
    ]
